string mesh_id
string mesh_path
float64 x
float64 y
float64 z
float64 r1
float64 r2
float64 r3
float64 r4
string rotation_format
float64 scale_x
float64 scale_y
float64 scale_z
float64 r
float64 g
float64 b
float64 a
string action          # "ADD" ou "REMOVE"
---
bool success
string message