# Request
float64[] joints           # Tableau des valeurs cibles (en radians)
bool is_relative           # True = ajoute ces angles aux angles actuels, False = va à ces angles absolus
bool execute               # True = planifie et bouge, False = planifie seulement

---
# Response
bool success
string message